services:
  seleniumminer:
    build:
      context: .
    restart: always
    # user: "1000:1000"
    networks:
      - main
    read_only: true
    volumes:
      - tmp:/tmp
    environment:
      - HOME=/tmp

networks:
  main:
    name: main
    external: true

volumes:
  tmp:
