services:
  seleniumminer:
    build:
      context: .
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - main

networks:
  main:
    name: main
    external: true
