services:
  seleniumminer:
    build:
      context: .
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - seleniumminer

networks:
  seleniumminer:
    name: seleniumminer
    external: true